package database

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"strings"
	"time"

	"moly/models"
)

// ClarificationCapture handles the Layer 3 workflow:
// 1. Detect clarification response in user message
// 2. Save response to database
// 3. Check for conflicts with existing preferences
// 4. Convert confirmed response to context_attributes
type ClarificationCapture struct {
	clarificationQRepo *ClarificationQuestionRepository
	clarificationRRepo *ClarificationResponseRepository
	conflictGate       *ConflictGate
	contextAttrRepo    *ContextAttributeRepository
}

// NewClarificationCapture creates a new capture handler
func NewClarificationCapture(db *Database) *ClarificationCapture {
	return &ClarificationCapture{
		clarificationQRepo: NewClarificationQuestionRepository(db),
		clarificationRRepo: NewClarificationResponseRepository(db),
		conflictGate:       NewConflictGate(db),
		contextAttrRepo:    NewContextAttributeRepository(db),
	}
}

// ClarificationResponse represents a user's answer to a clarification
type ClarificationAnswerCapture struct {
	QuestionID     string
	UserID         string
	ConversationID string
	ResponseText   string
	SelectedOption string
}

// SaveClarificationResponse saves user's response to a clarification question
// and converts it to a confirmed preference if no conflict
func (cc *ClarificationCapture) SaveClarificationResponse(
	capture *ClarificationAnswerCapture,
) (*ContextConflict, error) {

	log.Printf("[ClarificationCapture] Processing response to question: %s", capture.QuestionID)

	// 1. Save the clarification response
	response := &ClarificationResponse{
		ID:             fmt.Sprintf("resp_%d", time.Now().UnixNano()),
		QuestionID:     capture.QuestionID,
		UserID:         capture.UserID,
		ResponseText:   capture.ResponseText,
		SelectedOption: capture.SelectedOption,
		RespondedAt:    time.Now().Unix(),
		CreatedAt:      time.Now().Unix(),
	}

	err := cc.clarificationRRepo.SaveResponse(response)
	if err != nil {
		log.Printf("[ClarificationCapture] ❌ Failed to save clarification response: %v", err)
		return nil, fmt.Errorf("failed to save response: %w", err)
	}
	log.Printf("[ClarificationCapture] ✓ Saved clarification response: %s", response.ID)

	// 2. Mark question as answered
	err = cc.clarificationQRepo.MarkAnswered(capture.QuestionID)
	if err != nil {
		log.Printf("[ClarificationCapture] Warning: Failed to mark question as answered: %v", err)
	}

	// 3. Convert response to context attribute with conflict check
	// This is where we detect if the user's answer conflicts with previous values
	return cc.convertToConfirmedPreference(capture, response)
}

// convertToConfirmedPreference converts a clarification response to a confirmed preference
// Checks for conflicts before saving
func (cc *ClarificationCapture) convertToConfirmedPreference(
	capture *ClarificationAnswerCapture,
	response *ClarificationResponse,
) (*ContextConflict, error) {

	log.Printf("[ClarificationCapture] Converting response to confirmed preference")

	// Parse the response to extract key information
	// Different question types need different handling

	// For contact interest questions: "What interests do YOU share with [contact]?"
	// Response might be: "I like threesomes and doggy style"
	// We need to:
	// 1. Extract interests from response
	// 2. Check if we have previous interests for this contact
	// 3. If different: ask for confirmation via conflict gate
	// 4. If same or no previous: save directly

	// This is a simplified approach - in production we'd use LLM to parse the response
	// For now, we'll store the raw response as a confirmed preference

	attrType := "user_interest_alignment" // Generic type, refined by context

	// Check for conflict with existing preference
	conflict, err := cc.conflictGate.SaveWithConflictCheck(
		capture.UserID,
		capture.ConversationID,
		attrType,
		nil,                  // savedValue: would be loaded from DB in real implementation
		capture.ResponseText, // newValue
	)

	if err != nil {
		log.Printf("[ClarificationCapture] ❌ Conflict check failed: %v", err)
		return nil, err
	}

	if conflict != nil {
		log.Printf("[ClarificationCapture] ⚠️  Conflict detected, needs user resolution")
		return conflict, nil
	}

	// No conflict - save as confirmed preference
	attr := &ContextAttribute{
		ID:             0, // Auto-generated by database
		UserID:         capture.UserID,
		ConversationID: capture.ConversationID,
		FactType:       attrType,
		FactValue:      capture.ResponseText,
		AttributedTo:   "user_confirmed",
		Context:        "general",
		Confidence:     1.0, // 100% confident - user explicitly confirmed
		Source:         "clarification_response",
		Evidence:       fmt.Sprintf("Response to Q: %s", capture.QuestionID),
		Version:        1,
		CreatedAt:      time.Now().Unix(),
	}

	err = cc.contextAttrRepo.Save(attr)
	if err != nil {
		log.Printf("[ClarificationCapture] ❌ Failed to save confirmed preference: %v", err)
		return nil, fmt.Errorf("failed to save preference: %w", err)
	}

	log.Printf("[ClarificationCapture] ✓ Saved confirmed preference: %s = %s", attrType, capture.ResponseText)
	return nil, nil
}

// GetPendingClarifications retrieves unanswered clarification questions for a conversation
func (cc *ClarificationCapture) GetPendingClarifications(conversationID string) ([]interface{}, error) {
	if conversationID == "" {
		return nil, fmt.Errorf("conversationID is required")
	}

	log.Printf("[ClarificationCapture] Retrieving pending clarifications for conversation %s", conversationID)

	query := `
		SELECT id, user_id, conversation_id, clarification_type, question_text, context_notes,
		       options, priority, status, linked_facts, created_at, answered_at
		FROM clarification_questions
		WHERE conversation_id = ? AND status = 'pending'
		ORDER BY priority DESC, created_at DESC
	`

	rows, err := cc.clarificationQRepo.db.Query(query, conversationID)
	if err != nil {
		log.Printf("[ClarificationCapture] Failed to query pending questions: %v", err)
		return nil, fmt.Errorf("failed to query pending clarifications: %w", err)
	}
	defer rows.Close()

	var questions []interface{}
	for rows.Next() {
		question := &ClarificationQuestion{}
		var optionsJSON sql.NullString
		var factsJSON sql.NullString

		err := rows.Scan(
			&question.ID,
			&question.UserID,
			&question.ConversationID,
			&question.ClarificationType,
			&question.QuestionText,
			&question.ContextNotes,
			&optionsJSON,
			&question.Priority,
			&question.Status,
			&factsJSON,
			&question.CreatedAt,
			&question.AnsweredAt,
		)

		if err != nil {
			log.Printf("[ClarificationCapture] ERROR scanning question: %v", err)
			continue
		}

		if optionsJSON.Valid {
			if err := json.Unmarshal([]byte(optionsJSON.String), &question.Options); err != nil {
				log.Printf("[ClarificationCapture] ERROR parsing options for question %s: %v", question.ID, err)
			}
		}
		if factsJSON.Valid {
			if err := json.Unmarshal([]byte(factsJSON.String), &question.LinkedFacts); err != nil {
				log.Printf("[ClarificationCapture] ERROR parsing facts for question %s: %v", question.ID, err)
			}
		}

		questions = append(questions, question)
	}

	if err = rows.Err(); err != nil {
		log.Printf("[ClarificationCapture] ERROR iterating rows: %v", err)
		return nil, fmt.Errorf("error iterating clarification questions: %w", err)
	}

	log.Printf("[ClarificationCapture] ✓ Retrieved %d pending clarifications", len(questions))
	return questions, nil
}

// GetConfirmedPreferences retrieves all confirmed user preferences
func (cc *ClarificationCapture) GetConfirmedPreferences(userID string) (map[string]interface{}, error) {
	// This would query context_attributes where source = "clarification_response"
	// and AttributedTo = "user_confirmed"
	prefs := make(map[string]interface{})
	// Placeholder - will be fully implemented
	return prefs, nil
}

// DetectClarificationResponse attempts to match user message to pending clarifications
// Returns the question ID if matched, empty string if not a clarification response
func (cc *ClarificationCapture) DetectClarificationResponse(
	conversationID string,
	userMessage string,
) (string, error) {

	log.Printf("[ClarificationCapture] Attempting to detect if message is clarification response")
	log.Printf("[ClarificationCapture] Message: %.100s...", userMessage)

	// Get all questions for this conversation
	allQuestions, err := cc.clarificationQRepo.GetConversationQuestions(conversationID)
	if err != nil {
		log.Printf("[ClarificationCapture] Warning: Failed to get questions: %v", err)
		return "", err
	}

	// Filter for pending (unanswered) questions only
	var questions []*ClarificationQuestion
	for _, q := range allQuestions {
		if q.Status == "pending" {
			questions = append(questions, q)
		}
	}

	if len(questions) == 0 {
		log.Printf("[ClarificationCapture] No pending questions for this conversation")
		return "", nil
	}

	log.Printf("[ClarificationCapture] Found %d pending clarifications", len(questions))

	// For now, use simple heuristic:
	// - If there's exactly 1 pending question and message isn't empty, assume it's the answer
	// - In production, use LLM to verify message matches question context
	if len(questions) == 1 && len(userMessage) > 0 {
		log.Printf("[ClarificationCapture] ✓ Detected clarification response to: %s", questions[0].ID)
		return questions[0].ID, nil
	}

	// Multiple pending questions - would need LLM or user selection
	log.Printf("[ClarificationCapture] Multiple pending questions, cannot auto-detect")
	return "", nil
}

// IsLikelyClarificationResponse performs a simple check: is there a pending question?
// Used as a quick gate before doing more expensive matching
func (cc *ClarificationCapture) IsLikelyClarificationResponse(conversationID string) bool {
	allQuestions, err := cc.clarificationQRepo.GetConversationQuestions(conversationID)
	if err != nil {
		return false
	}

	// Check if any are pending
	for _, q := range allQuestions {
		if q.Status == "pending" {
			return true
		}
	}
	return false
}

// DetectClarificationType classifies the type of clarification the user is providing
// Returns nil if message is not a clarification
func (cc *ClarificationCapture) DetectClarificationType(message string) *models.ClarificationContext {
	log.Printf("[ClarificationCapture] Detecting clarification type for message")

	// Pattern 1: User restates with explicit markers
	if strings.Contains(strings.ToLower(message), "i said") ||
		strings.Contains(strings.ToLower(message), "i meant") ||
		strings.Contains(strings.ToLower(message), "actually") {
		log.Printf("[ClarificationCapture] Detected: correction (explicit restatement)")
		return &models.ClarificationContext{
			Type:       "correction",
			Confidence: 0.95,
		}
	}

	// Pattern 2: Subject clarification with explicit names/pronouns
	if (strings.Contains(message, " is ") || strings.Contains(message, "is ")) &&
		(strings.ContainsAny(message, "Se,Kate,John") ||
			strings.Contains(strings.ToLower(message), "she") ||
			strings.Contains(strings.ToLower(message), "he")) {
		log.Printf("[ClarificationCapture] Detected: subject_clarification")
		return &models.ClarificationContext{
			Type:       "subject_clarification",
			Confidence: 0.85,
		}
	}

	return nil
}

// ProcessClarification applies the correction to the database based on clarification type
func (cc *ClarificationCapture) ProcessClarification(
	clarif *models.ClarificationContext,
	message string,
	userID string,
	conversationID string,
) error {

	if clarif == nil {
		return fmt.Errorf("clarification context is required")
	}

	log.Printf("[ClarificationCapture] Processing clarification type: %s", clarif.Type)

	switch clarif.Type {
	case "correction":
		log.Printf("[ClarificationCapture] Handling correction clarification")
		// Mark that we're correcting previous extraction
		// Save response with metadata indicating it's a correction
		attr := &ContextAttribute{
			ID:             0,
			UserID:         userID,
			ConversationID: conversationID,
			FactType:       "correction",
			FactValue:      message,
			AttributedTo:   "user_confirmed",
			Context:        "general",
			Confidence:     1.0,
			Source:         "clarification_correction",
			Evidence:       message,
			Version:        1,
			CreatedAt:      time.Now().Unix(),
		}

		err := cc.contextAttrRepo.Save(attr)
		if err != nil {
			log.Printf("[ClarificationCapture] Error saving correction: %v", err)
			return err
		}
		log.Printf("[ClarificationCapture] ✓ Correction saved and marked as confirmed")

	case "subject_clarification":
		log.Printf("[ClarificationCapture] Handling subject clarification")
		attr := &ContextAttribute{
			ID:             0,
			UserID:         userID,
			ConversationID: conversationID,
			FactType:       "subject_clarification",
			FactValue:      message,
			AttributedTo:   "user_confirmed",
			Context:        "general",
			Confidence:     1.0,
			Source:         "clarification_subject",
			Evidence:       message,
			Version:        1,
			CreatedAt:      time.Now().Unix(),
		}

		err := cc.contextAttrRepo.Save(attr)
		if err != nil {
			log.Printf("[ClarificationCapture] Error saving subject clarification: %v", err)
			return err
		}
		log.Printf("[ClarificationCapture] ✓ Subject clarification saved")

	case "contradiction":
		log.Printf("[ClarificationCapture] Handling contradiction (requires follow-up)")
		clarif.RequiresFollowUp = true
		return nil
	}

	return nil
}
