package database

import (
	"fmt"
	"log"
	"time"
)

// ClarificationCapture handles the Layer 3 workflow:
// 1. Detect clarification response in user message
// 2. Save response to database
// 3. Check for conflicts with existing preferences
// 4. Convert confirmed response to context_attributes
type ClarificationCapture struct {
	clarificationQRepo *ClarificationQuestionRepository
	clarificationRRepo *ClarificationResponseRepository
	conflictGate       *ConflictGate
	contextAttrRepo    *ContextAttributeRepository
}

// NewClarificationCapture creates a new capture handler
func NewClarificationCapture(db *Database) *ClarificationCapture {
	return &ClarificationCapture{
		clarificationQRepo: NewClarificationQuestionRepository(db),
		clarificationRRepo: NewClarificationResponseRepository(db),
		conflictGate:       NewConflictGate(db),
		contextAttrRepo:    NewContextAttributeRepository(db),
	}
}

// ClarificationResponse represents a user's answer to a clarification
type ClarificationAnswerCapture struct {
	QuestionID     string
	UserID         string
	ConversationID string
	ResponseText   string
	SelectedOption string
}

// SaveClarificationResponse saves user's response to a clarification question
// and converts it to a confirmed preference if no conflict
func (cc *ClarificationCapture) SaveClarificationResponse(
	capture *ClarificationAnswerCapture,
) (*ContextConflict, error) {

	log.Printf("[ClarificationCapture] Processing response to question: %s", capture.QuestionID)

	// 1. Save the clarification response
	response := &ClarificationResponse{
		ID:             fmt.Sprintf("resp_%d", time.Now().UnixNano()),
		QuestionID:     capture.QuestionID,
		UserID:         capture.UserID,
		ResponseText:   capture.ResponseText,
		SelectedOption: capture.SelectedOption,
		RespondedAt:    time.Now().Unix(),
		CreatedAt:      time.Now().Unix(),
	}

	err := cc.clarificationRRepo.SaveResponse(response)
	if err != nil {
		log.Printf("[ClarificationCapture] ❌ Failed to save clarification response: %v", err)
		return nil, fmt.Errorf("failed to save response: %w", err)
	}
	log.Printf("[ClarificationCapture] ✓ Saved clarification response: %s", response.ID)

	// 2. Mark question as answered
	err = cc.clarificationQRepo.MarkAnswered(capture.QuestionID)
	if err != nil {
		log.Printf("[ClarificationCapture] Warning: Failed to mark question as answered: %v", err)
	}

	// 3. Convert response to context attribute with conflict check
	// This is where we detect if the user's answer conflicts with previous values
	return cc.convertToConfirmedPreference(capture, response)
}

// convertToConfirmedPreference converts a clarification response to a confirmed preference
// Checks for conflicts before saving
func (cc *ClarificationCapture) convertToConfirmedPreference(
	capture *ClarificationAnswerCapture,
	response *ClarificationResponse,
) (*ContextConflict, error) {

	log.Printf("[ClarificationCapture] Converting response to confirmed preference")

	// Parse the response to extract key information
	// Different question types need different handling

	// For contact interest questions: "What interests do YOU share with [contact]?"
	// Response might be: "I like threesomes and doggy style"
	// We need to:
	// 1. Extract interests from response
	// 2. Check if we have previous interests for this contact
	// 3. If different: ask for confirmation via conflict gate
	// 4. If same or no previous: save directly

	// This is a simplified approach - in production we'd use LLM to parse the response
	// For now, we'll store the raw response as a confirmed preference

	attrType := "user_interest_alignment" // Generic type, refined by context

	// Check for conflict with existing preference
	conflict, err := cc.conflictGate.SaveWithConflictCheck(
		capture.UserID,
		capture.ConversationID,
		attrType,
		nil, // savedValue: would be loaded from DB in real implementation
		capture.ResponseText, // newValue
	)

	if err != nil {
		log.Printf("[ClarificationCapture] ❌ Conflict check failed: %v", err)
		return nil, err
	}

	if conflict != nil {
		log.Printf("[ClarificationCapture] ⚠️  Conflict detected, needs user resolution")
		return conflict, nil
	}

	// No conflict - save as confirmed preference
	attr := &ContextAttribute{
		ID:             0, // Auto-generated by database
		UserID:         capture.UserID,
		ConversationID: capture.ConversationID,
		FactType:       attrType,
		FactValue:      capture.ResponseText,
		AttributedTo:   "user_confirmed",
		Context:        "general",
		Confidence:     1.0, // 100% confident - user explicitly confirmed
		Source:         "clarification_response",
		Evidence:       fmt.Sprintf("Response to Q: %s", capture.QuestionID),
		Version:        1,
		CreatedAt:      time.Now().Unix(),
	}

	err = cc.contextAttrRepo.Save(attr)
	if err != nil {
		log.Printf("[ClarificationCapture] ❌ Failed to save confirmed preference: %v", err)
		return nil, fmt.Errorf("failed to save preference: %w", err)
	}

	log.Printf("[ClarificationCapture] ✓ Saved confirmed preference: %s = %s", attrType, capture.ResponseText)
	return nil, nil
}

// GetPendingClarifications retrieves unanswered clarification questions for a conversation
func (cc *ClarificationCapture) GetPendingClarifications(conversationID string) ([]interface{}, error) {
	// This would query clarification_questions table for status = "pending"
	// For now, return empty - will be implemented when wired into main.go
	return []interface{}{}, nil
}

// GetConfirmedPreferences retrieves all confirmed user preferences
func (cc *ClarificationCapture) GetConfirmedPreferences(userID string) (map[string]interface{}, error) {
	// This would query context_attributes where source = "clarification_response"
	// and AttributedTo = "user_confirmed"
	prefs := make(map[string]interface{})
	// Placeholder - will be fully implemented
	return prefs, nil
}
