package tools

import (
	"context"
	"fmt"
	"log"
	"strings"
)

// MockLLMClient - Mock LLM client for testing (no external dependencies, instant responses)
type MockLLMClient struct {
	Model            string
	ResponseMode     string // "success", "fallback", "error"
	CallCount        int
	LastRequest      *LLMRequest
	ResponseOverride map[string]string // Override responses by prompt keyword
}

// NewMockLLMClient - Create new mock LLM client
func NewMockLLMClient() *MockLLMClient {
	log.Printf("[MockLLMClient] Initialized in test mode")
	return &MockLLMClient{
		Model:            "mock-model",
		ResponseMode:     "success",
		ResponseOverride: make(map[string]string),
	}
}

// NewMockLLMClientWithMode - Create mock client with specific response mode
func NewMockLLMClientWithMode(mode string) *MockLLMClient {
	client := NewMockLLMClient()
	client.ResponseMode = mode
	return client
}

// Call - Mock implementation of LLMClient.Call (instant, deterministic)
func (m *MockLLMClient) Call(ctx context.Context, req *LLMRequest) (*LLMResponse, error) {
	m.CallCount++
	m.LastRequest = req

	log.Printf("[MockLLMClient] Call #%d: mode=%s prompt_len=%d", m.CallCount, m.ResponseMode, len(req.UserPrompt))

	// Check for context cancellation
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}

	// Check for response overrides based on keywords
	for keyword, response := range m.ResponseOverride {
		if strings.Contains(strings.ToLower(req.UserPrompt), strings.ToLower(keyword)) {
			log.Printf("[MockLLMClient] Using override for keyword: %s", keyword)
			return &LLMResponse{
				Content:          response,
				StopReason:       "end_turn",
				TokensUsed:       len(strings.Fields(response)),
				CostUSD:          0.001,
				ProcessingTimeMs: 10,
				Model:            m.Model,
			}, nil
		}
	}

	// Generate response based on mode and prompt content
	switch m.ResponseMode {
	case "success":
		return m.generateSuccessResponse(req)
	case "fallback":
		return m.generateFallbackResponse(req)
	case "error":
		return nil, fmt.Errorf("mock LLM error: simulated failure")
	default:
		return m.generateSuccessResponse(req)
	}
}

// generateSuccessResponse - Generate a realistic success response
func (m *MockLLMClient) generateSuccessResponse(req *LLMRequest) (*LLMResponse, error) {
	prompt := strings.ToLower(req.UserPrompt)
	var content string

	// Generate context-aware responses
	if strings.Contains(prompt, "suggest") || strings.Contains(prompt, "advice") {
		content = m.generateSuggestion(req.UserPrompt)
	} else if strings.Contains(prompt, "question") || strings.Contains(prompt, "gather") {
		content = m.generateContextQuestion(req.UserPrompt)
	} else if strings.Contains(prompt, "extract") {
		content = m.generateExtraction(req.UserPrompt)
	} else if strings.Contains(prompt, "intent") || strings.Contains(prompt, "intention") {
		content = m.generateIntentionAnalysis(req.UserPrompt)
	} else if strings.Contains(prompt, "risk") || strings.Contains(prompt, "concern") {
		content = m.generateRiskAnalysis(req.UserPrompt)
	} else {
		content = "This is a helpful response from the mock LLM. In production, this would come from Claude, OpenAI, or a local LLM."
	}

	return &LLMResponse{
		Content:          content,
		StopReason:       "end_turn",
		TokensUsed:       len(strings.Fields(content)) + 10,
		CostUSD:          0.0001,
		ProcessingTimeMs: 5, // Instant in tests
		Model:            m.Model,
	}, nil
}

// generateFallbackResponse - Generate fallback heuristic response
func (m *MockLLMClient) generateFallbackResponse(req *LLMRequest) (*LLMResponse, error) {
	content := "[HEURISTIC FALLBACK] This response was generated by heuristics because the LLM was unavailable. " +
		"In production, this would only appear when the LLM provider is offline."

	return &LLMResponse{
		Content:          content,
		StopReason:       "fallback",
		TokensUsed:       len(strings.Fields(content)),
		CostUSD:          0,
		ProcessingTimeMs: 0,
		Model:            "heuristic-fallback",
	}, nil
}

// generateSuggestion - Generate mock suggestions
func (m *MockLLMClient) generateSuggestion(prompt string) string {
	suggestions := []string{
		"Here are three suggested ways to phrase that:\n1. Be direct and honest about your feelings.\n2. Start with appreciation before sharing your concern.\n3. Ask for their perspective first.",
		"Consider these communication options:\n1. \"I've been thinking about this and want to talk with you about...\"\n2. \"I value our relationship and want to be honest about...\"\n3. \"Can we sit down and discuss something important?\"",
		"You might try saying:\n1. \"I appreciate you, and I want to be honest about my concerns.\"\n2. \"I've noticed something and would like to talk about it.\"\n3. \"How would you feel if we discussed...\"",
	}
	return suggestions[m.CallCount%len(suggestions)]
}

// generateContextQuestion - Generate context-gathering questions
func (m *MockLLMClient) generateContextQuestion(prompt string) string {
	questions := []string{
		"To give you better advice, could you tell me: What's your communication style? How do you prefer to handle difficult conversations? What's the relationship context?",
		"I'd like to understand better: How well do you know this person? What have past conversations been like? What's your main concern right now?",
		"Help me understand: What would success look like for you in this conversation? What are you hoping will happen? How important is this relationship to you?",
	}
	return questions[m.CallCount%len(questions)]
}

// generateExtraction - Generate mock context extraction
func (m *MockLLMClient) generateExtraction(prompt string) string {
	extraction := `{
  "aboutMe": {
    "communicationStyle": "thoughtful but direct",
    "values": ["authenticity", "honesty", "growth"],
    "preferredTone": "warm and genuine",
    "notes": "Prefers conversations grounded in real feelings"
  },
  "contact": {
    "name": "Sarah",
    "relationship": "close friend",
    "characteristics": ["thoughtful", "creative", "sensitive"],
    "notes": "Values deep conversations and honesty"
  },
  "confidence": 0.85
}`
	return extraction
}

// generateIntentionAnalysis - Generate intention analysis
func (m *MockLLMClient) generateIntentionAnalysis(prompt string) string {
	analysis := `{
  "intentions": ["express feelings", "strengthen relationship", "seek advice"],
  "emotionalTone": "vulnerable but hopeful",
  "primaryGoal": "authentic conversation",
  "confidence": 0.88
}`
	return analysis
}

// generateRiskAnalysis - Generate risk assessment
func (m *MockLLMClient) generateRiskAnalysis(prompt string) string {
	analysis := `{
  "riskLevel": "low",
  "concerns": [],
  "recommendations": ["proceed with honesty"],
  "educationalPoints": ["Being vulnerable strengthens relationships"],
  "confidence": 0.92
}`
	return analysis
}

// SetResponseOverride - Set a custom response for a specific keyword
func (m *MockLLMClient) SetResponseOverride(keyword, response string) {
	m.ResponseOverride[keyword] = response
	log.Printf("[MockLLMClient] Set override for keyword: %s", keyword)
}

// ClearOverrides - Clear all response overrides
func (m *MockLLMClient) ClearOverrides() {
	m.ResponseOverride = make(map[string]string)
	log.Printf("[MockLLMClient] Cleared all overrides")
}

// GetCallCount - Get number of times Call was invoked
func (m *MockLLMClient) GetCallCount() int {
	return m.CallCount
}

// GetLastRequest - Get the last request made
func (m *MockLLMClient) GetLastRequest() *LLMRequest {
	return m.LastRequest
}

// Reset - Reset mock state
func (m *MockLLMClient) Reset() {
	m.CallCount = 0
	m.LastRequest = nil
	m.ResponseOverride = make(map[string]string)
	log.Printf("[MockLLMClient] Reset to initial state")
}
